<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="INBLRWIT238540" name="Credentials.InvalidLogin$ValidateCredentialsTest" tests="2" failures="0" timestamp="16 Mar 2020 05:22:08 GMT" time="0.033" errors="1">
  <testcase name="launchSelectBrowser" time="0.033" classname="Credentials.InvalidLogin$ValidateCredentialsTest">
    <error type="java.io.FileNotFoundException" message=".\testData\commonData.properties (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: .\testData\commonData.properties (The system cannot find the path specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.edureka.project.genericLib.FileLib.getCommonData(FileLib.java:27)
at com.edureka.project.genericLib.BaseClass.launchSelectBrowser(BaseClass.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at Credentials.TestRunner.main(TestRunner.java:11)
]]>
    </error>
  </testcase> <!-- launchSelectBrowser -->
  <testcase name="InvalidcredentialTest" time="0.000" classname="Credentials.InvalidLogin$ValidateCredentialsTest">
    <skipped/>
  </testcase> <!-- InvalidcredentialTest -->
</testsuite> <!-- Credentials.InvalidLogin$ValidateCredentialsTest -->
